// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: pictoclash.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Bio      string `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Pronouns string `protobuf:"bytes,4,opt,name=pronouns,proto3" json:"pronouns,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pictoclash_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pictoclash_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pictoclash_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetPronouns() string {
	if x != nil {
		return x.Pronouns
	}
	return ""
}

type TestUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestUserReq) Reset() {
	*x = TestUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pictoclash_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestUserReq) ProtoMessage() {}

func (x *TestUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_pictoclash_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestUserReq.ProtoReflect.Descriptor instead.
func (*TestUserReq) Descriptor() ([]byte, []int) {
	return file_pictoclash_proto_rawDescGZIP(), []int{1}
}

type TestUserRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *TestUserRes) Reset() {
	*x = TestUserRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pictoclash_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestUserRes) ProtoMessage() {}

func (x *TestUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_pictoclash_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestUserRes.ProtoReflect.Descriptor instead.
func (*TestUserRes) Descriptor() ([]byte, []int) {
	return file_pictoclash_proto_rawDescGZIP(), []int{2}
}

func (x *TestUserRes) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_pictoclash_proto protoreflect.FileDescriptor

var file_pictoclash_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x69, 0x63, 0x74, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x70, 0x69, 0x63, 0x74, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x68, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6e, 0x6f, 0x75, 0x6e, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x6e, 0x6f, 0x75, 0x6e, 0x73, 0x22, 0x0d, 0x0a,
	0x0b, 0x54, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x33, 0x0a, 0x0b,
	0x54, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x69, 0x63, 0x74,
	0x6f, 0x63, 0x6c, 0x61, 0x73, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x32, 0x82, 0x01, 0x0a, 0x0a, 0x50, 0x69, 0x63, 0x74, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x68,
	0x12, 0x36, 0x0a, 0x04, 0x4e, 0x6f, 0x6f, 0x70, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x70, 0x69, 0x63, 0x74, 0x6f, 0x63, 0x6c, 0x61, 0x73,
	0x68, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x70, 0x69, 0x63, 0x74, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x68, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pictoclash_proto_rawDescOnce sync.Once
	file_pictoclash_proto_rawDescData = file_pictoclash_proto_rawDesc
)

func file_pictoclash_proto_rawDescGZIP() []byte {
	file_pictoclash_proto_rawDescOnce.Do(func() {
		file_pictoclash_proto_rawDescData = protoimpl.X.CompressGZIP(file_pictoclash_proto_rawDescData)
	})
	return file_pictoclash_proto_rawDescData
}

var file_pictoclash_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pictoclash_proto_goTypes = []interface{}{
	(*User)(nil),          // 0: pictoclash.User
	(*TestUserReq)(nil),   // 1: pictoclash.TestUserReq
	(*TestUserRes)(nil),   // 2: pictoclash.TestUserRes
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_pictoclash_proto_depIdxs = []int32{
	0, // 0: pictoclash.TestUserRes.user:type_name -> pictoclash.User
	3, // 1: pictoclash.Pictoclash.Noop:input_type -> google.protobuf.Empty
	1, // 2: pictoclash.Pictoclash.TestUser:input_type -> pictoclash.TestUserReq
	3, // 3: pictoclash.Pictoclash.Noop:output_type -> google.protobuf.Empty
	2, // 4: pictoclash.Pictoclash.TestUser:output_type -> pictoclash.TestUserRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pictoclash_proto_init() }
func file_pictoclash_proto_init() {
	if File_pictoclash_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pictoclash_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pictoclash_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pictoclash_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestUserRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pictoclash_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pictoclash_proto_goTypes,
		DependencyIndexes: file_pictoclash_proto_depIdxs,
		MessageInfos:      file_pictoclash_proto_msgTypes,
	}.Build()
	File_pictoclash_proto = out.File
	file_pictoclash_proto_rawDesc = nil
	file_pictoclash_proto_goTypes = nil
	file_pictoclash_proto_depIdxs = nil
}
