services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "25432:5432"

volumes:
  pgdata:
