// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ClashEvent struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

type ClashTeam struct {
	ID           int64  `json:"id"`
	TeamName     string `json:"team_name"`
	ClashEventID int64  `json:"clash_event_id"`
}

type Pronoun struct {
	ID             int64  `json:"id"`
	SubjectPronoun string `json:"subject_pronoun"`
	ObjectPronoun  string `json:"object_pronoun"`
}

type User struct {
	ID             uuid.UUID      `json:"id"`
	Username       string         `json:"username"`
	Bio            sql.NullString `json:"bio"`
	PronounsID     sql.NullInt64  `json:"pronouns_id"`
	CustomPronouns sql.NullString `json:"custom_pronouns"`
}
